drop policy if exists wallet_transaction_records_select_self_or_staff on wallet_transaction_records;
drop policy if exists paid_message_delivery_requests_select_party_or_staff on paid_message_delivery_requests;
drop policy if exists messages_select_conversation_member_or_staff on messages;
drop policy if exists conversation_members_select_member_or_staff on conversation_members;
drop policy if exists conversations_select_member_or_staff on conversations;
drop policy if exists live_replay_assets_select_creator_pass_holder_or_staff on live_replay_assets;
drop policy if exists live_chat_messages_select_participant_or_staff on live_chat_messages;
drop policy if exists live_passes_select_holder_creator_or_staff on live_passes;
drop policy if exists live_pass_purchase_requests_select_buyer_creator_or_staff on live_pass_purchase_requests;
drop policy if exists live_rooms_select_creator_or_staff on live_rooms;
drop policy if exists referral_commissions_select_referrer_or_staff on referral_commissions;
drop policy if exists referral_attributions_select_party_or_staff on referral_attributions;
drop policy if exists referral_tokens_select_creator_or_staff on referral_tokens;
drop policy if exists payment_ledger_entries_select_account_owner_or_staff on payment_ledger_entries;
drop policy if exists entitlement_events_select_owner_or_staff on entitlement_events;
drop policy if exists entitlements_select_self_or_staff on entitlements;
drop policy if exists payment_settlement_attempts_select_owner_or_staff on payment_settlement_attempts;
drop policy if exists payment_intents_select_self_or_staff on payment_intents;
drop policy if exists content_access_rules_select_visible_creator_or_staff on content_access_rules;
drop policy if exists media_assets_select_visible_creator_or_staff on media_assets;
drop policy if exists content_items_select_visible_creator_or_staff on content_items;
drop policy if exists wallet_link_challenges_select_self_or_staff on wallet_link_challenges;
drop policy if exists wallets_select_self_or_staff on wallets;
drop policy if exists age_verifications_select_self_or_staff on age_verifications;
drop policy if exists audit_events_select_actor_or_staff on audit_events;
drop policy if exists idempotency_keys_select_staff on idempotency_keys;
drop policy if exists provider_webhook_receipts_select_staff on provider_webhook_receipts;
drop policy if exists provider_events_select_staff on provider_events;
drop policy if exists staff_permissions_select_self_or_staff on staff_permissions;
drop policy if exists staff_memberships_select_self_or_staff on staff_memberships;
drop policy if exists profiles_select_public_self_or_staff on profiles;
drop policy if exists users_select_self_or_staff on users;

alter table payment_settlement_attempts disable row level security;
alter table payment_intents disable row level security;
alter table content_access_rules disable row level security;
alter table media_assets disable row level security;
alter table content_items disable row level security;
alter table wallet_link_challenges disable row level security;
alter table wallets disable row level security;
alter table age_verifications disable row level security;
alter table audit_events disable row level security;
alter table idempotency_keys disable row level security;
alter table provider_webhook_receipts disable row level security;
alter table provider_events disable row level security;
alter table staff_permissions disable row level security;
alter table staff_memberships disable row level security;
alter table profiles disable row level security;
alter table users disable row level security;

revoke execute on function private.is_staff_member() from authenticated;
revoke execute on function private.current_app_user_id() from authenticated;
revoke usage on schema private from authenticated;
drop function if exists private.is_staff_member();
drop function if exists private.current_app_user_id();
drop schema if exists private;
