import { parsePublicWebEnv } from "@veel/config/public";

export function readPublicWebEnv() {
  return parsePublicWebEnv({
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
    NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID: process.env.NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID,
    NEXT_PUBLIC_TURNKEY_API_BASE_URL: process.env.NEXT_PUBLIC_TURNKEY_API_BASE_URL,
    NEXT_PUBLIC_TURNKEY_AUTH_PROXY_URL: process.env.NEXT_PUBLIC_TURNKEY_AUTH_PROXY_URL,
    NEXT_PUBLIC_TURNKEY_AUTH_PROXY_CONFIG_ID: process.env.NEXT_PUBLIC_TURNKEY_AUTH_PROXY_CONFIG_ID,
    NEXT_PUBLIC_SOLANA_CHAIN: process.env.NEXT_PUBLIC_SOLANA_CHAIN,
    NEXT_PUBLIC_SOLANA_RPC_URL: process.env.NEXT_PUBLIC_SOLANA_RPC_URL,
    NEXT_PUBLIC_SOLANA_RPC_SUBSCRIPTIONS_URL: process.env.NEXT_PUBLIC_SOLANA_RPC_SUBSCRIPTIONS_URL,
    NEXT_PUBLIC_ENABLE_E2E_AUTH: process.env.NEXT_PUBLIC_ENABLE_E2E_AUTH,
    NEXT_PUBLIC_EMBEDDED_WALLET_RUNTIME_ENABLED: process.env.NEXT_PUBLIC_EMBEDDED_WALLET_RUNTIME_ENABLED
  });
}
